GINI-467 Add properties for java_opts per cloud environment.

diff --git a/tomcat/templates/default/tomcat-init.erb b/tomcat/templates/default/tomcat-init.erb
--- a/tomcat/templates/default/tomcat-init.erb
+++ b/tomcat/templates/default/tomcat-init.erb
@@ -66,7 +66,6 @@ export JAVA_HOME
 USER_DATA_FILE="/var/lib/cloud/instance/user-data.txt"
 if [ -e $USER_DATA_FILE ]; then
     source $USER_DATA_FILE
-    export RAILS_ENV=$CLOUD_STACK
 fi
 
 # Directory where the Tomcat binary distribution resides
@@ -84,7 +83,16 @@ TOMCAT_SECURITY=no
 # It also looks like the default heap size of 64M is not enough for most cases
 # so the maximum heap size is set to 128M
 if [ -z "$JAVA_OPTS" ]; then
-        JAVA_OPTS="-Djava.awt.headless=true -XX:MaxPermSize=256m -Xmx1024m"
+    JAVA_OPTS="-Djava.awt.headless=true"
+    if [ $CLOUD_STACK == "nightly" ]; then
+        JAVA_OPTS="$JAVA_OPTS <%= @java_opts_nightly %>"
+    elif [ $CLOUD_STACK == "acc" ]; then
+        JAVA_OPTS="$JAVA_OPTS <%= @java_opts_acc %>"
+    elif [ $CLOUD_STACK == "prod" ]; then
+        JAVA_OPTS="$JAVA_OPTS <%= @java_opts_prod %>"
+    else
+        JAVA_OPTS="$JAVA_OPTS -XX:MaxPermSize=256m -Xmx1024m"
+    fi
 fi
 
 # End of variables that can be overwritten in $DEFAULT
@@ -125,145 +133,144 @@ if [ -z "${JSSE_HOME}" -a -r "${JAVA_HOME}/jre/lib/jsse.jar" ]; then
 fi
 
 catalina_sh() {
-        # Escape any double quotes in the value of JAVA_OPTS
-        JAVA_OPTS="$(echo $JAVA_OPTS | sed 's/\"/\\\"/g')"
+    # Escape any double quotes in the value of JAVA_OPTS
+    JAVA_OPTS="$(echo $JAVA_OPTS | sed 's/\"/\\\"/g')"
 
-        AUTHBIND_COMMAND=""
-        if [ "$AUTHBIND" = "yes" -a "$1" = "start" ]; then
-                JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true"
-                AUTHBIND_COMMAND="/usr/bin/authbind --deep /bin/bash -c "
-        fi
+    AUTHBIND_COMMAND=""
+    if [ "$AUTHBIND" = "yes" -a "$1" = "start" ]; then
+            JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true"
+            AUTHBIND_COMMAND="/usr/bin/authbind --deep /bin/bash -c "
+    fi
 
-        # Define the command to run Tomcat's catalina.sh as a daemon
-        # set -a tells sh to export assigned variables to spawned shells.
-        TOMCAT_SH="set -a; JAVA_HOME=\"$JAVA_HOME\"; source \"$DEFAULT\"; \
-                CATALINA_HOME=\"$CATALINA_HOME\"; \
-		              CATALINA_BASE=\"$CATALINA_BASE\"; \
-		                JAVA_OPTS=\"$JAVA_OPTS\"; \
-		                CATALINA_PID=\"$CATALINA_PID\"; \
-		                CATALINA_TMPDIR=\"$CATALINA_TMPDIR\"; \
-		                LANG=\"$LANG\"; JSSE_HOME=\"$JSSE_HOME\"; \
-		                cd \"$CATALINA_BASE\"; \
-		                \"$CATALINA_SH\" $@"
+    # Define the command to run Tomcat's catalina.sh as a daemon
+    # set -a tells sh to export assigned variables to spawned shells.
+    TOMCAT_SH="set -a; JAVA_HOME=\"$JAVA_HOME\"; source \"$DEFAULT\"; \
+            CATALINA_HOME=\"$CATALINA_HOME\"; \
+            CATALINA_BASE=\"$CATALINA_BASE\"; \
+            JAVA_OPTS=\"$JAVA_OPTS\"; \
+            CATALINA_PID=\"$CATALINA_PID\"; \
+            CATALINA_TMPDIR=\"$CATALINA_TMPDIR\"; \
+            LANG=\"$LANG\"; JSSE_HOME=\"$JSSE_HOME\"; \
+            cd \"$CATALINA_BASE\"; \
+            \"$CATALINA_SH\" $@"
 
-		        if [ "$AUTHBIND" = "yes" -a "$1" = "start" ]; then
-		                TOMCAT_SH="'$TOMCAT_SH'"
-		        fi
+    if [ "$AUTHBIND" = "yes" -a "$1" = "start" ]; then
+            TOMCAT_SH="'$TOMCAT_SH'"
+    fi
 
-		        # Run the catalina.sh script as a daemon
-		        set +e
-		        touch "$CATALINA_PID" "$CATALINA_BASE"/logs/catalina.out
-		        chown $TOMCAT_USER "$CATALINA_PID" "$CATALINA_BASE"/logs/catalina.out
-		        start-stop-daemon --start -b -u "$TOMCAT_USER" -g "$TOMCAT_GROUP" \
-		                -c "$TOMCAT_USER" -d "$CATALINA_TMPDIR" \
-		                -x /bin/bash -- -c "$AUTHBIND_COMMAND $TOMCAT_SH"
-		        status="$?"
-		        set +a -e
-		        return $status
-			}
+    # Run the catalina.sh script as a daemon
+    set +e
+    touch "$CATALINA_PID" "$CATALINA_BASE"/logs/catalina.out
+    chown $TOMCAT_USER "$CATALINA_PID" "$CATALINA_BASE"/logs/catalina.out
+    start-stop-daemon --start -b -u "$TOMCAT_USER" -g "$TOMCAT_GROUP" \
+            -c "$TOMCAT_USER" -d "$CATALINA_TMPDIR" \
+            -x /bin/bash -- -c "$AUTHBIND_COMMAND $TOMCAT_SH"
+    status="$?"
+    set +a -e
+    return $status
+}
 
-			case "$1" in
-			  start)
-			        if [ -z "$JAVA_HOME" ]; then
-			                log_failure_msg "no JDK found - please set JAVA_HOME"
-			                exit 1
-			        fi
+case "$1" in
+start)
+    if [ -z "$JAVA_HOME" ]; then
+            log_failure_msg "no JDK found - please set JAVA_HOME"
+            exit 1
+    fi
 
-			        if [ ! -d "$CATALINA_BASE/conf" ]; then
-			                log_failure_msg "invalid CATALINA_BASE: $CATALINA_BASE"
-			                exit 1
-			        fi
+    if [ ! -d "$CATALINA_BASE/conf" ]; then
+            log_failure_msg "invalid CATALINA_BASE: $CATALINA_BASE"
+            exit 1
+    fi
 
-			        log_daemon_msg "Starting $DESC" "$NAME"
-			        if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
-			                --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
-			                >/dev/null; then
+    log_daemon_msg "Starting $DESC" "$NAME"
+    if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
+            --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
+            >/dev/null; then
 
-			                # Remove / recreate JVM_TMP directory
-			                rm -rf "$JVM_TMP"
-			                mkdir -p "$JVM_TMP" || {
-						                        log_failure_msg "could not create JVM temporary directory"
-						                        exit 1
-						                }
-						                chown $TOMCAT_USER "$JVM_TMP"
+            # Remove / recreate JVM_TMP directory
+            rm -rf "$JVM_TMP"
+            mkdir -p "$JVM_TMP" || {
+                    log_failure_msg "could not create JVM temporary directory"
+                    exit 1
+            }
+            chown $TOMCAT_USER "$JVM_TMP"
 
-						                catalina_sh start $SECURITY
-						                sleep 5
-						                if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
-						                        --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
-						                        >/dev/null; then
-						                        if [ -f "$CATALINA_PID" ]; then
-						                                rm -f "$CATALINA_PID"
-						                        fi
-						                        log_end_msg 1
-						                else
-						                        log_end_msg 0
-						                fi
-						        else
-						                log_progress_msg "(already running)"
-						                log_end_msg 0
-						        fi
-							       ;;
-							  stop)
-							        log_daemon_msg "Stopping $DESC" "$NAME"
+            catalina_sh start $SECURITY
+            sleep 5
+            if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
+                    --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
+                    >/dev/null; then
+                    if [ -f "$CATALINA_PID" ]; then
+                            rm -f "$CATALINA_PID"
+                    fi
+                    log_end_msg 1
+            else
+                    log_end_msg 0
+            fi
+    else
+            log_progress_msg "(already running)"
+            log_end_msg 0
+    fi
+   ;;
+stop)
+    log_daemon_msg "Stopping $DESC" "$NAME"
 
-							        set +e
-							        if [ -f "$CATALINA_PID" ]; then
-							                start-stop-daemon --stop --pidfile "$CATALINA_PID" \
-							                        --user "$TOMCAT_USER" \
-							                        --retry=TERM/20/KILL/5 >/dev/null
-							                if [ $? -eq 1 ]; then
-							                        log_progress_msg "$DESC is not running but pid file exists, cleaning up"
-							                elif [ $? -eq 3 ]; then
-							                        PID="`cat $CATALINA_PID`"
-							                        log_failure_msg "Failed to stop $NAME (pid $PID)"
-							                        exit 1
-							                fi
-							                rm -f "$CATALINA_PID"
-							                rm -rf "$JVM_TMP"
-							        else
-							                log_progress_msg "(not running)"
-							        fi
-								       log_end_msg 0
-								        set -e
-								        ;;
-								   status)
-								        set +e
-								        start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
-								                --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
-								                >/dev/null 2>&1
-								        if [ "$?" = "0" ]; then
+    set +e
+    if [ -f "$CATALINA_PID" ]; then
+            start-stop-daemon --stop --pidfile "$CATALINA_PID" \
+                    --user "$TOMCAT_USER" \
+                    --retry=TERM/20/KILL/5 >/dev/null
+            if [ $? -eq 1 ]; then
+                    log_progress_msg "$DESC is not running but pid file exists, cleaning up"
+            elif [ $? -eq 3 ]; then
+                    PID="`cat $CATALINA_PID`"
+                    log_failure_msg "Failed to stop $NAME (pid $PID)"
+                    exit 1
+            fi
+            rm -f "$CATALINA_PID"
+            rm -rf "$JVM_TMP"
+    else
+            log_progress_msg "(not running)"
+    fi
+   log_end_msg 0
+    set -e
+    ;;
+status)
+    set +e
+    start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
+            --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
+            >/dev/null 2>&1
+    if [ "$?" = "0" ]; then
 
-								                if [ -f "$CATALINA_PID" ]; then
-								                    log_success_msg "$DESC is not running, but pid file exists."
-								                        exit 1
-								                else
-								                    log_success_msg "$DESC is not running."
-								                        exit 3
-								                fi
-								        else
-								                log_success_msg "$DESC is running with pid `cat $CATALINA_PID`"
-								        fi
-								        set -e
-								        ;;
-										 restart|force-reload)
-										        if [ -f "$CATALINA_PID" ]; then
-										                $0 stop
-										                sleep 1
-										        fi
-										        $0 start
-										        ;;
-										  try-restart)
-										        if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
-										                --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
-										                >/dev/null; then
-										                $0 start
-										        fi
-										        ;;
-										  *)
-										        log_success_msg "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
-										        exit 1
-										        ;;
-										esac
-
-										exit 0
+            if [ -f "$CATALINA_PID" ]; then
+                log_success_msg "$DESC is not running, but pid file exists."
+                exit 1
+            else
+                log_success_msg "$DESC is not running."
+                exit 3
+            fi
+    else
+            log_success_msg "$DESC is running with pid `cat $CATALINA_PID`"
+    fi
+    set -e
+    ;;
+restart|force-reload)
+       if [ -f "$CATALINA_PID" ]; then
+               $0 stop
+               sleep 1
+       fi
+       $0 start
+       ;;
+try-restart)
+      if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
+               --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
+               >/dev/null; then
+               $0 start
+      fi
+      ;;
+      *)
+      log_success_msg "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
+      exit 1
+      ;;
+esac
+exit 0
