Add monitoring options to startup script

diff --git a/tomcat/templates/default/tomcat-init.erb b/tomcat/templates/default/tomcat-init.erb
--- a/tomcat/templates/default/tomcat-init.erb
+++ b/tomcat/templates/default/tomcat-init.erb
@@ -127,6 +127,8 @@ fi
 CATALINA_PID="/var/run/$NAME.pid"
 CATALINA_SH="$CATALINA_HOME/bin/catalina.sh"
 
+MONITORING_OPTS="-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=3333"
+
 # Look for Java Secure Sockets Extension (JSSE) JARs
 if [ -z "${JSSE_HOME}" -a -r "${JAVA_HOME}/jre/lib/jsse.jar" ]; then
     JSSE_HOME="${JAVA_HOME}/jre/"
@@ -148,6 +150,7 @@ catalina_sh() {
             CATALINA_HOME=\"$CATALINA_HOME\"; \
             CATALINA_BASE=\"$CATALINA_BASE\"; \
             JAVA_OPTS=\"$JAVA_OPTS\"; \
+            CATALINA_OPTS=\"$CATALINA_OPTS\"; \
             CATALINA_PID=\"$CATALINA_PID\"; \
             CATALINA_TMPDIR=\"$CATALINA_TMPDIR\"; \
             LANG=\"$LANG\"; JSSE_HOME=\"$JSSE_HOME\"; \
@@ -194,6 +197,49 @@ start)
                     exit 1
             }
             chown $TOMCAT_USER "$JVM_TMP"
+
+            catalina_sh start $SECURITY
+            sleep 5
+            if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
+                    --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
+                    >/dev/null; then
+                    if [ -f "$CATALINA_PID" ]; then
+                            rm -f "$CATALINA_PID"
+                    fi
+                    log_end_msg 1
+            else
+                    log_end_msg 0
+            fi
+    else
+            log_progress_msg "(already running)"
+            log_end_msg 0
+    fi
+   ;;
+start-monitor)
+    if [ -z "$JAVA_HOME" ]; then
+            log_failure_msg "no JDK found - please set JAVA_HOME"
+            exit 1
+    fi
+
+    if [ ! -d "$CATALINA_BASE/conf" ]; then
+            log_failure_msg "invalid CATALINA_BASE: $CATALINA_BASE"
+            exit 1
+    fi
+
+    log_daemon_msg "Starting $DESC" "$NAME"
+    if start-stop-daemon --test --start --pidfile "$CATALINA_PID" \
+            --user $TOMCAT_USER --exec "$JAVA_HOME/bin/java" \
+            >/dev/null; then
+
+            # Remove / recreate JVM_TMP directory
+            rm -rf "$JVM_TMP"
+            mkdir -p "$JVM_TMP" || {
+                    log_failure_msg "could not create JVM temporary directory"
+                    exit 1
+            }
+            chown $TOMCAT_USER "$JVM_TMP"
+
+            CATALINA_OPTS="$CATALINA_OPTS $MONITORING_OPTS"
 
             catalina_sh start $SECURITY
             sleep 5
